config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'contacts#index'
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
        @contacts=Contact.all
    end

    def show
        @contact=Contact.find(params[:id])
    end

    def new
        @contact=Contact.new
    end

    def create
        Contact.create(contact_params)
        redirect_to contacts_url
    end

    def edit
        @contact=Contact.find(params[:id])
    end

    def update
        @contact=Contact.find(params[:id])
        @contact.update(contact_params)
        redirect_to contacts_url
    end

    def destroy
        @contact=Contact.find(params[:id])
        @contact.destroy
        redirect_to contacts_url
    end

    private
    def contact_params
        params.require(:contact).permit(:name,:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_back.html.erb
<%= link_to 'back',contacts_path %>

app/views/contacts/_form.html.erb
<%= form_for anAction do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :number %>
        <%= f.number_field :number %>
    </div>
    <%= f.submit %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit contact</h1>
<%= render partial: 'back' %>
<%= render partial: 'form', locals:{ anAction: @contact} %>

app/views/contacts/index.html.erb
<h1>Phonebook</h1>
<%= link_to 'new contact',new_contact_path %>
<% @contacts.each do |contact| %>
    <li>Name: <%= contact.name %> | #: <%= contact.number %> | <%= link_to 'show',contact_path(contact) %> | <%= link_to 'edit',edit_contact_path(contact) %> | <%= link_to 'delete',contact_path(contact),method: :delete, data: {confirm:"Are you sure you want to delete this contact?"} %></li>
<% end %>

app/views/contacts/new.html.erb
<h1>New contact</h1>
<%= render partial: 'back' %>
<%= render partial: 'form', locals:{ anAction: @contact} %>

app/views/contacts/show.html.erb
<h1>Contact</h1>
<%= render partial: 'back' %>
<p>Contact name: <%= @contact.name %></p>
<p>Contact #: <%= @contact.number %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourthRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>